import { Link } from "react-router-dom";
import { Icon } from "@/components/icons/icons";

export default function Terms() {
  return (
    <div className="shell section-pad">
      <div className="mx-auto max-w-2xl">
        <Link
          to="/"
          className="mb-8 inline-flex items-center gap-2 text-ink-500 hover:text-ink-800"
        >
          <Icon.ArrowLeft width={14} height={14} />
          <span className="mono-label">back</span>
        </Link>

        <div className="relative overflow-hidden rounded-[20px] border border-line bg-surface">
          <div className="absolute inset-0 bg-dotpaper-thick opacity-40" />
          <div className="absolute left-0 right-0 top-0 h-[3px] bg-verdant-500" />
          <div className="relative p-8 sm:p-10">
            <h1 className="font-display text-3xl text-ink-900">Terms of Service</h1>
            <p className="mt-2 text-sm text-ink-500">Last updated August 2026</p>

            <div className="mt-8 space-y-6 text-[15px] leading-relaxed text-ink-700">
              <section>
                <h2 className="mb-2 font-display text-lg text-ink-900">
                  1. What drop&grow Is
                </h2>
                <p>
                  drop&grow is a space where you drop ideas and six specialized agents shape
                  them into plans. The agent engine processes your input on your own
                  device and your ideas stay yours.
                </p>
              </section>

              <section>
                <h2 className="mb-2 font-display text-lg text-ink-900">2. Your Ideas</h2>
                <p>
                  You retain full ownership of everything you create in drop&grow. When you
                  mark an idea as private, only you can see it. When you publish to the
                  community, you choose to share it, but you never give up ownership. You
                  can delete your ideas at any time.
                </p>
              </section>

              <section>
                <h2 className="mb-2 font-display text-lg text-ink-900">
                  3. Agent Processing
                </h2>
                <p>
                  The six agents (Nova, Palette, Quill, Circuit, Apex, Ledger) and the
                  Planner run a processing pipeline. Your content is processed within the
                  platform and is not sent to third-party services for training or analysis.
                </p>
              </section>

              <section>
                <h2 className="mb-2 font-display text-lg text-ink-900">
                  4. Community Ideas
                </h2>
                <p>
                  Ideas published to the community are visible to all drop&grow users. Others
                  can view, branch from, and contribute to community ideas. The original
                  author retains ownership and can unpublish at any time.
                </p>
              </section>

              <section>
                <h2 className="mb-2 font-display text-lg text-ink-900">
                  5. No Warranties
                </h2>
                <p>
                  drop&grow is provided as-is. The agent outputs are suggestions, not
                  guarantees. We do not warrant that any plan generated by the agents will
                  produce specific results. Use your judgment.
                </p>
              </section>

              <section>
                <h2 className="mb-2 font-display text-lg text-ink-900">
                  6. Changes to These Terms
                </h2>
                <p>
                  We may update these terms. If we make material changes, we will notify
                  you through the platform. Continued use of drop&grow after changes
                  constitutes acceptance of the updated terms.
                </p>
              </section>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
